[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  
[[plugins]]
  package = "netlify-plugin-algolia-index"
  [plugins.inputs]
      exclude = ['/admin', '/404.html']

