backend:
  name: git-gateway
  branch: master
  
logo_url: https://administrasi.net/img/untitled.png
  
media_folder: "img/"
public_folder: "/img/"

publish_mode: editorial_workflow
collections:

  - name: "artikel"
    label: "Artikel"
    folder: "_posts/artikel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      
